<?php

namespace YannickMahe\SelfHostedVideosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubtitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubtitleRepository extends EntityRepository
{
}
