imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator: ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

#app/config/config.yml
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        less:
            node:       /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to:   "\.less$"
        cssrewrite: ~
    assets:
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/less/bootstrap.less
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/less/responsive.less
            filters:
                - less
                - cssrewrite
            output: bundles/braincraftedbootstrap/css/bootstrap.compiled.css
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-transition.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-alert.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-button.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-carousel.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-collapse.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-dropdown.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-modal.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-tooltip.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-popover.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-scrollspy.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-tab.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-typeahead.js
                - %kernel.root_dir%/../web/bundles/braincraftedbootstrap/js/bootstrap-affix.js
            output: bundles/braincraftedbootstrap/js/bootstrap.compiled.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# FOSUserBundlep
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: YannickMahe\SelfHostedVideosBundle\Entity\User