yannick_mahe_self_hosted_videos_upload_page:
    pattern:  /upload
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:index }
    requirements:
        _method:  GET

yannick_mahe_self_hosted_videos_add_from_file:
    pattern:  /filesystem
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:addFromFile }
    requirements:
        _method:  GET

yannick_mahe_self_hosted_videos_add_video_from_file:
    pattern:  /add_from_file
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:addVideoFromFile }
    requirements:
        _method:  POST

yannick_mahe_self_hosted_videos_list:
    pattern:  /
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:list }
    requirements:
        _method:  GET

yannick_mahe_self_hosted_videos_video:
    pattern:  /video/{video_id}/{subtitle_id}
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:video, subtitle_id: false }
    requirements:
        _method:  GET

yannick_mahe_self_hosted_videos_videos_json:
    pattern:  /videos.json
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:videosJson }
    requirements:
        _method:  GET

yannick_mahe_self_hosted_videos_series_json:
    pattern:  /series.json
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:seriesJson }
    requirements:
        _method:  GET


yannick_mahe_self_hosted_videos_delete:
    pattern:  /video/delete/{video_id}
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:delete }
    requirements:
        _method:  DELETE

yannick_mahe_self_hosted_videos_upload:
    pattern:  /upload
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:upload }
    requirements:
        _method:  POST

yannick_mahe_self_hosted_videos_subtitle_add:
    pattern: /subtitle_add
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Subtitle:add }
    requirements:
        _method:  POST