yannick_mahe_self_hosted_videos_upload_page:
    pattern:  /upload
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:index }
    requirements:
        _method:  GET

yannick_mahe_self_hosted_videos_add_from_file:
    pattern:  /filesystem
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:addFromFile }
    requirements:
        _method:  GET

yannick_mahe_self_hosted_videos_list:
    pattern:  /
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:list }
    requirements:
        _method:  GET

yannick_mahe_self_hosted_videos_video:
    pattern:  /video/{video_id}
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:video }
    requirements:
        _method:  GET

yannick_mahe_self_hosted_videos_delete:
    pattern:  /video/delete/{video_id}
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:delete }
    requirements:
        _method:  DELETE

yannick_mahe_self_hosted_videos_upload:
    pattern:  /upload
    defaults: { _controller: YannickMaheSelfHostedVideosBundle:Default:upload }
    requirements:
        _method:  POST